############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/03/2024        #
############################
# Cluster setup

version: "3.8"

services: # Services configuration

  webserver1: # Webserver 1 configuration
    container_name: webserver1
    image: ubuntu:22.04
    ports:
      - "8080:80"
    networks:
      internal:
        ipv4_address: 10.0.1.1
    volumes:
      - webserver1:/var/www/html
    restart: always

volumes: # Volumes configuration

  webserver1: # Webserver 1 volume configuration
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/cluster1/webservices/webserver1'

networks: # Network configuration
  
  internal: # Internal network configuration
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8


# Step 1: Go to the directory
# cd DockerComposeCluster

# Step 3: Run the docker compose file
# docker-compose -f cluster_setup_docker-compose.yml up