######################
# Van Elias De Hondt #
######################
# Webapp Redis & Node.js

web:
  build: .
  command: node /myapp/example.js
  links:
    - redis
  ports:
    - 8080:80
redis:
  image: redis:latest