############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/03/2024        #
############################
# Webapp Redis & Node.js

web:
  build: .
  command: node /myapp/example.js
  links:
    - redis
  ports:
    - 8080:80
redis:
  image: redis:latest